### ISSUE TITLE
Is this supposed to happen? 

### ISSUE THREAD

**Issue by MrMcY3et** [warlord-hash/EvenHarderMuck#3]
Im playing muck with thins mod but I cant craft bark. Is this supposed to happen?
Thank you for listening to my question, Sincerely MrMcY3et.

**Comment by warlord-hash** [comment]
Probably a problem with 1.0.6, please check if this happens on v1.0.61

**Comment by warlord-hash** [comment]
Issue should be resoled with 1.0.62

**Comment by MrMcY3et** [comment]
It works now. Thanks for the fix!
